#!/bin/bash

## if your ldconf or your LD_LIBRARY_PATH don't include the path to 
## libgds3d uncomment and edit following line properly
#LD_LIBRARY_PATH=~/lib:$LD_LIBRARY_PATH

## if your PATH environment variable doesn't include the path to the
## gds2vrm executabel the path has to be added
GDS2VRML=gds2vrml

## extract cell-name
if [ -f $1 ] ; then
    CELL=`basename $1 .gds`
    echo "--> converting cell $CELL " 
else
    echo "usage: create_vrml <file.gds> [<top-cell-name>]"
    echo "       top-cell-name has to be included if it differs from filename"
    echo "ERROR: parameter $1 is not a valid filename"
    exit
fi

## check for top-cell name
if [ "x$2" == "x" ] ; then
    ## attention Cadence converts top-cell names if it contains unsupported signs 
    ## like dots 
    TOP=`echo ${CELL} | sed -e "s/\./\_/"`
else
    TOP=$2
fi

## removes existing WRL files
if [ -f ${CELL}.wrl ] ; then
    rm -f ${CELL}.wrl
fi

if [ -f ${CELL}.wrl.gz ] ; then
    rm -f ${CELL}.wrl.gz
fi


${GDS2VRML} -i ${CELL}.gds -o ${CELL}.wrl -p simple.txt -t ${TOP}

# view3dscene can read gzipped files!
gzip ${CELL}.wrl

